version: "3.9"

services:
  backend:
    build: ./backend
    container_name: filehive-backend
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env
    networks:
      - filehive-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: filehive-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - filehive-network
    restart: unless-stopped

networks:
  filehive-network:
    external: true
